image: php:8.3-cli

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Installing dependencies..."
    - cd source
    - apt-get update && apt-get install -y git unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer  # Устанавливаем Composer
    - composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - echo "Build complete."
    - echo "Running PHPUnit tests..."
    - ./vendor/bin/phpunit
    - echo "PHPUnit tests completed."

unit-test-job:
  stage: test
  script:
    - echo "Running PHPUnit tests..."
    - echo "PHPUnit tests completed."

lint-test-job:
  stage: test
  script:
    - echo "Running PHP linting..."
    - echo "PHP linting completed."

deploy-job:
  stage: deploy
  when: manual
  only:
    - main
  before_script:
    - apt-get update && apt-get install -y openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan 193.124.33.190 >> ~/.ssh/known_hosts
  script:
    - ssh -i ~/.ssh/id_rsa root@193.124.33.190 "cd /home/docker/sleep/build && ./deploy.sh"
    - echo "Deploy script executed successfully."